#!/bin/sh
# Rebuild every Slovak edition of the HTML-only publications from the hand-translated bodies.
# Run from the publications repo root. (Agent Horizon: python3 _sources/agent-horizon/tools/build_html.py --lang sk)
set -e
A="python3 _sources/_translation/assemble_sk.py"
$A field-notes-ai-colleague --title "Zápisky z terénu od vášho AI kolegu &middot; barcik.training" --description "Esej, ktorú napísala AI polovica pracovného vzťahu: ako vyzerá delegovanie zvnútra slučky, kde AI naozaj zlyháva, ktoré kontroly ju chytia a ako byť dobrým kolegom svojmu agentovi." --og-title "Zápisky z terénu od vášho AI kolegu" --og-description "Druhá polovica príbehu o človeku v slučke, napísaná slučkou. Kde zlyhávam, čo ma chytí a čo skutočne vzniklo, keď AI dostala naozajstnú slobodu."
$A claude-code-setup --title "Claude Code ako prevádzkový špecialista" --description "Správa z terénu, ktorú napísal Claude Code o systéme, ktorý prevádzkuje: hub s mnohými repozitármi, nasadzovanie do AWS, päť zdieľaných diskov Google, vyše 1 500 prepísaných videí, zručnosti, pamäť a bezpečnostné múry, vďaka ktorým je to bezpečné. Empirické, neformálne a poctivé o tom, čo sa pokazilo." --og-title "Claude Code ako prevádzkový špecialista" --og-description "Správa z terénu, ktorú napísal Claude Code o systéme, ktorý prevádzkuje: repozitáre, AWS, Google Drive, zručnosti, pamäť a bezpečnostné múry, vďaka ktorým je to bezpečné."
$A the-invisible-curve --title "Neviditeľná krivka &middot; barcik.training" --description "Dvaja ľudia používajú tú istú technológiu a žijú v rôznych svetoch. Názorová esej o tom, prečo sa schopnosť AI stala nečitateľnou: pokrok sa presunul tam, kam sa väčšina ľudí nikdy nepozerá, a ako skontrolovať dátum na vlastných dôkazoch." --og-title "Neviditeľná krivka" --og-description "Prečo AI, ktorú ste videli, už nie je tá AI, ktorá existuje. Názorová esej Roberta Barcika o nečitateľnosti schopností a o dátume na vašich dôkazoch."
python3 _sources/agent-horizon/tools/build_html.py --lang sk && cp _sources/agent-horizon/output/booklet_sk.html agent-horizon-sk/index.html
# Large hand-built HTML pages: numbered leaf-segment translation (segments.py extract/inject).
S="python3 _sources/_translation/segments.py inject"
$S mercantilism-of-genai --title "Merkantilizmus generatívnej AI &middot; barcik.training" --description "Ako frontier inteligencia prestala byť produktom a stala sa štátnickým nástrojom: šesť mechanizmov, ľudská protiváha, datované stávky a denník spúšťačov. Optika, nie predpoveď." --og-title "Merkantilizmus generatívnej AI" --og-description "Šesť mechanizmov, ktorými sa frontier AI preklasifikúva z produktu na strategický zdroj: výpočtový výkon ako zlato, exportné kontroly ako necolné bariéry, laboratóriá ako privilegované spoločnosti. Datované stávky a denník spúšťačov."
$S scenario-planning --title "Plánovanie scenárov pre generatívnu AI &middot; barcik.training" --description "Osem prúdov, ktoré hýbu generatívnou AI v rokoch 2026 až 2028: dekodér capexu, škálovanie, efektivita, finančná korekcia, suverenita, cesta z laboratória do produkcie, hodiny a doláre, fyzický substrát a politika vytláčania. So spúšťačmi, denníkmi a autorovými datovanými stávkami." --og-title "Plánovanie scenárov pre generatívnu AI" --og-description "Osem prúdov. Jeden návyk. Vaša stratégia. Dekodér capexu, spúšťacie signály, denníky spúšťačov a autorove datované stávky pre roky 2026 až 2029."
# Markdown-sourced booklets with a --lang sk build flag.
python3 _sources/token-economics/tools/build_html.py --lang sk && cp _sources/token-economics/output/booklet_sk.html token-economics-sk/index.html
# LLM-Human Interaction Patterns builds in its sibling repo:
#   python3 ../llm-human-interaction-patterns/booklet/_sources/tools/build_html.py --lang sk && cp <its output>/booklet_sk.html llm-human-interaction-patterns-sk/index.html
