#!/bin/sh
# Rebuild every Slovak edition of the HTML-only publications from the hand-translated bodies.
# Run from the publications repo root. (Agent Horizon: python3 _sources/agent-horizon/tools/build_html.py --lang sk)
set -e
A="python3 _sources/_translation/assemble_sk.py"
$A field-notes-ai-colleague --title "Zápisky z terénu od vášho AI kolegu &middot; barcik.training" --description "Esej, ktorú napísala AI polovica pracovného vzťahu: ako vyzerá delegovanie zvnútra slučky, kde AI naozaj zlyháva, ktoré kontroly ju chytia a ako byť dobrým kolegom svojmu agentovi." --og-title "Zápisky z terénu od vášho AI kolegu" --og-description "Druhá polovica príbehu o človeku v slučke, napísaná slučkou. Kde zlyhávam, čo ma chytí a čo skutočne vzniklo, keď AI dostala naozajstnú slobodu."
$A claude-code-setup --title "Claude Code ako prevádzkový špecialista" --description "Správa z terénu, ktorú napísal Claude Code o systéme, ktorý prevádzkuje: hub s mnohými repozitármi, nasadzovanie do AWS, päť zdieľaných diskov Google, vyše 1 500 prepísaných videí, zručnosti, pamäť a bezpečnostné múry, vďaka ktorým je to bezpečné. Empirické, neformálne a poctivé o tom, čo sa pokazilo." --og-title "Claude Code ako prevádzkový špecialista" --og-description "Správa z terénu, ktorú napísal Claude Code o systéme, ktorý prevádzkuje: repozitáre, AWS, Google Drive, zručnosti, pamäť a bezpečnostné múry, vďaka ktorým je to bezpečné."
$A the-invisible-curve --title "Neviditeľná krivka &middot; barcik.training" --description "Dvaja ľudia používajú tú istú technológiu a žijú v rôznych svetoch. Názorová esej o tom, prečo sa schopnosť AI stala nečitateľnou: pokrok sa presunul tam, kam sa väčšina ľudí nikdy nepozerá, a ako skontrolovať dátum na vlastných dôkazoch." --og-title "Neviditeľná krivka" --og-description "Prečo AI, ktorú ste videli, už nie je tá AI, ktorá existuje. Názorová esej Roberta Barcika o nečitateľnosti schopností a o dátume na vašich dôkazoch."
python3 _sources/agent-horizon/tools/build_html.py --lang sk && cp _sources/agent-horizon/output/booklet_sk.html agent-horizon-sk/index.html
